spring:

  h2:
    console:
      enabled: true
      path: "/h2"


  liquibase:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: "classpath:db/changelog/db.changelog-1.0.0.yaml"
    # Liquibase usará su propio DataSource JDBC si se provee esta URL (el proyecto usa R2DBC para runtime)
    url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false"
    user: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"


adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "crediya_solicitudes"
    username: "root"
    password: "mysql"


cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"