server:
  port: ${SERVER_PORT:8081}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
security:
  jwt:
    secret: ${JWT_KEY_SECRET:AQUI VA EL KEY SECRET DEFAULT}
app:
  issuer: ${JWT_ISSUER:"http://localhost:8080"} # lo genera el ms de autenticacion
  audience: "autenticacion" # no lo estoy usando :D
logging:
  pattern:
    level: "%5p [${spring.application.name}] [cid:%X{correlationId}]"
  config: ${LOGGING_CONFIG_FILE:classpath:logback-spring.xml}
  file:
    path: ${LOG_PATH:build/logs}


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:  #TODO incluir esto en los restConsumer
      enabled: true


cors:
  allowed-origins: "*"

adapter:
  restconsumer:
    timeout: 5000
    baseurl: ${BASE_URL_MS_AUTH:"http://localhost:8080"}


resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
